### ISSUE TITLE
Final Fantasy Type 0 D-Pad oversensitive

### ISSUE THREAD

**Issue by butstevetho** [Freakler/psp-camera_patch_lite#11]
With the camera patch plugin enabled, the D Pad controls in Final Fantasy Type-0 become extremely sensitive. One tap will make your cursor cycle through a menu rapidly. After reinstalling adrenaline i figured out the problem only occurs when the camera patch plugin is enabled. My other games (crisis core etc) seem to work fine. I am using the latest version of Adrenaline on a 1000 model vita.

Is there a workaround for this or will i simply have to disable FF Type 0's entry in the plugin .ini?

Edit: it seems this is because the D pad originally controls the camera AND the menu, and when the plugin is enabled it registers every input echo (or double input?) resulting in multiple presses in one tap. I have disabled type 0 in the ini file because this is unplayable. Maybe it should not be in the "compatible" list?

**Comment by Freakler** [comment]
Thanks, sounds about right. I commented it out :/
