### ISSUE TITLE
Why is Assassin's Creed set to false but Prince of Persia to true?

### ISSUE THREAD

**Issue by ghost** [Freakler/psp-camera_patch_lite#12]
There is a native remastered plugin by FloW for Prince of Persia games, but not one for Assassin's Creed. Are you sure you haven't mixed those two games up in the .ini file? AC should probably be set to true, and PoP games to false.

**Comment by Freakler** [comment]
He did in fact make one for AC but removed it from his collection it seems. I'll just set it to true then
